### ISSUE TITLE
Is react-native 0.4.x supported?

### ISSUE THREAD

**Issue by psbanka** [auth0/Lock.ReactNative#2]
Hi, there. I noticed that the Seed Project specifies version `0.3.11`, but when upgrading to React-Native `0.4.4`, I got quite a few errors. Is this version of react-native supported? 

Thanks,
—Peter

**Comment by kvieira90** [comment]
Any update on this? Having the same issue here

**Comment by adamjv90** [comment]
Showing 19 errors when trying to build with newer version of react native

**Comment by hzalaz** [comment]
The answer to the original question is no, 0.4.x is not supported yet. I'll try to check it out tomorrow since both RN & Xcode have new versions. @kvieira90 @adamjv90 if you can provide the list of errors will help us to figure out how long it will take to fix them

**Comment by adamjv90** [comment]
current installed version of react native is ^0.11.4. i started my project running react-native init . Once the react-native init command had finished i created a podfile at  $(project_name)/ios/Podfile and ran pod install. From there i opened up the xcworkspace and finished up the rest of the setup instructions. 

The errors messages i received when attempting to run are:

/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:26:60: Expected '>'
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:26:61: Expected member name or ';' after declaration specifiers
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:26:1: Property requires fields to be named
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:26:84: Expected ';' at end of declaration list
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:26:84: Expected identifier or '('
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:27:55: Expected '>'
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:27:56: Expected member name or ';' after declaration specifiers
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:27:1: Property requires fields to be named
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:27:56: Expected ';' at end of declaration list
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:27:56: Expected identifier or '('
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:26:63: Interface type cannot be statically allocated
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:35:9: Use of undeclared identifier '_callbacks'
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:41:10: Property 'callbacks' not found on object of type 'A0Alert *'
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:42:11: Property 'buttons' not found on object of type 'A0Alert *'
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:78:11: Property 'buttons' not found on object of type 'A0Alert *'
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:99:11: Property 'buttons' not found on object of type 'A0Alert *'
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:106:28: Property 'buttons' not found on object of type 'A0Alert *'
/Users/adam/Desktop/Meetup/ios/Pods/Lock/Pod/Classes/CoreUI/A0Alert.m:107:43: Property 'callbacks' not found on object of type 'A0Alert *'

I am unfamiliar with a lot of the xcode environment still since i am entering it from the web world.I am more then willing to help in any way possible and to my abilities. I really appreciate you helping me figure this one out and am excited to integrate lock with the rest of my native react application!

**Comment by adamjv90** [comment]
I was using xcode 6, could that be the issue? upgrading now.

**Comment by adamjv90** [comment]
any update on this?

**Comment by hzalaz** [comment]
@adamjv90 didn't have a lot of time last week but I tried it today and it's working without any issues for me. 
* What version of Xcode do you have installed (run `xcodebuild -version`)? 
* What version of LockReact and Lock pods are you using?

**Comment by adamjv90** [comment]
Xcode 6.3
Build version 6D570

pod --version
0.38.2

and i installed LockReact by adding the following to my podfile 
pod 'LockReact', '~> 0.4'

I was able to get the native ios version of lock working and for now am using that then loading up a react app once the user is authenticated.

**Comment by hzalaz** [comment]
I'd recommend to update to Xcode 7 but besides that, it should work because you are already using the native iOS version of Lock which is wrapped by LockReact. If you can try it again let me know if you still se those compile errors, remove the `Pods` folder and run `pod install` again just to be sure.

**Comment by adamjv90** [comment]
Thanks for all your help, i was able to get it working!
