### ISSUE TITLE
Clarify Instructions for react-native cli

### ISSUE THREAD

**Issue by cancan101** [auth0/Lock.ReactNative#7]
These instructions:
>Then copy A0LockReactModule.h and A0LockReactModule.m to your Xcode project, and make sure they added to your app's target.

are different from what is shown here: https://auth0.com/docs/native-platforms/ios-reactnative

**Comment by cancan101** [comment]
Also is that module's file names inconsistent with:
```js
var Lock = require('NativeModules').LockReactModule;
```

**Comment by hzalaz** [comment]
They are different cause in the docs we show the code to use in the page and in the README we just instruct to download those files. The module name is wrong in the README though but I need to check this lib again since RN changed a couple of things in the latest version.

**Comment by cancan101** [comment]
Why are the instructions different based on the projected being created with the RN CLI or not?

Also where should those files be copied?

**Comment by hzalaz** [comment]
Because if it's created with the CLI, React itself is embedded in the Xcode project instead of use a iOS dependency management so you need to download those files and add them the Xcode project RN CLI created for you directly. If you start creating an Xcode project first and then adding RN you don't need to do that since you probably use the platform dependency management tool (Cococapods in this case). 

The files should be added to your Xcode Project, so copy them to its folder and then add them from Xcode making sure they are added to the application's target so they are compiled and included in the binary when running the app

**Comment by cancan101** [comment]
@hzalaz Looks like there are [some changes in new version of RN around Cocoa Pods](https://github.com/facebook/react-native/releases/tag/v0.13.0).

**Comment by cancan101** [comment]
@hzalaz Where do those files have to be copied? Into some subdirectory (`NativeModules`)? Or top level?
The usage looks like:
```
var Lock = require('NativeModules').LockReactModule;
```

**Comment by hzalaz** [comment]
If you are not familiar with how Xcode works you should follow the instructions in the quickstart https://auth0.com/docs/quickstart/native-mobile/ios-reactnative/no-api/ instead of manually adding the file since it involves not only copying to the root folder of the Xcode project as I said before but telling Xcode to compile those files in the application target.

About the usage, seems RN changed again how to include the module in JSX so you need to do this instead

```js
var Lock = require('react-native').NativeModules.LockReactModule;
```

**Comment by cancan101** [comment]
Should that be: `var Lock = require('react-native').NativeModules.LockReactModule;` or `var Lock = require('react-native').NativeModules.A0LockReactModule;` ?

**Comment by hzalaz** [comment]
Following the quickstart the former, if you take the classes from this repo it should be `LockReact` since it's exporting the module with 
``` objc
RCT_EXPORT_MODULE(LockReact);
```

**Comment by cancan101** [comment]
I believe that I have added the files following the directions on the quick-start. Building fails with:
```
In file included from /Users/alex/RNAuth0/ios/A0LockReactModule.m:23:
/Users/alex/RNAuth0/ios/A0LockReactModule.h:24:9: fatal error: 'React/Base/RCTBridgeModule.h' file not found
#import <React/Base/RCTBridgeModule.h>
```

**Comment by hzalaz** [comment]
We'll need to revise this lib since RN changes a lot of thing on each release

**Comment by cancan101** [comment]
and when/ if I change `#import <React/Base/RCTBridgeModule.h>` to `#import <RCTBridgeModule.h>` then I get: https://github.com/auth0/Lock.ReactNative/issues/8.

**Comment by hzalaz** [comment]
We'll be reviewing this #9 since CP is not the way to include it now. I am closing this in favor of that issue

**Comment by cancan101** [comment]
@hzalaz To be clear I think RN should no longer be included with CP but I don't think there is an issue including components using CP.

**Comment by hzalaz** [comment]
CocoaPods is one of the most used Dependency Management tool for iOS and you are still working in iOS (through RN), and this library is a wrapper of the native iOS SDK so it you'll need CP to include it. (We'll add support for the other major DM tool Carthage soon so you can pick either of them)

I've read a little what they changed and seems they cleaned up some of the mess they have when including React libs in a way no sane iOS dev would. You'll still use CP as a way to avoid dealing with Xcode and it's build system but the RN version will be obtained from node_modules

**Comment by hzalaz** [comment]
It will be something like this https://github.com/facebook/react-native-fbsdk/tree/master/react-native-fbsdklogin#cocoapods

**Comment by cancan101** [comment]
In thinking about this, why do you even need CP at all?
For example, see: https://github.com/umhan35/react-native-search-bar.

**Comment by hzalaz** [comment]
To add the native part (in that case the static lib) to your app project you need to add two files to all this
```
To link this library, please follow the first two steps in the Linking Libraries (iOS) guide on React Native website. The .xcodeproj file is in node_modules/react-native-search-bar/. In the end, you should have RNSearchBar.xcodeproj in the Libaries group on Xcode and libRNSearchBar.a in the Link Binary With Libraries section inside the Build Phases tab of your project target.
```

instead of declaring a file like this:

```
source 'https://github.com/CocoaPods/Specs.git'
pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => 'node_modules/react-native'
pod 'react-native-search-bar', :path => 'node_modules/react-native-search-bar'
```

and run a single command `pod install`

I always prefer the latter specially since most users of RN are not familiar with iOS dev tools so the former will bring a lot more issues and possible errors, I am a iOS dev and make errors all the time cause Xcode has a lousy UI to deal with third party libs
